### ISSUE TITLE
SIGSEGV on Android (Termux) 

### ISSUE THREAD

**Issue by bartlomiejb** [89z/mech#10]
When built on Android in Termux:
```
~/.../cmd/youtube $ ./youtube gjtMDtA0N7Y
POST https://www.youtube.com/youtubei/v1/player GET https://rr4---sn-u2oxu-3ufd.googlevideo.com/vide...m-ert0QvGXtzVHfhaIJejuH9juEnFvVXTdL7lNZNxQ%3D%3D
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x5997c3b884]
                                                goroutine 1 [running]:
github.com/89z/format.Content(...)                      /data/data/com.termux/files/home/go/pkg/mod/github.com/89z/format@v1.16.7/format.go:123 github.com/89z/mech/youtube.Format.Write({0xf7, {0x4000438e00, 0x377}, {0x4000019650, 0x18}, 0xbf8ee, 0x500, 0x2d0, 0x1674c00}, {0x5997ca7420, ...})                                                    /data/data/com.termux/files/home/mech/mech-master/youtube/format.go:46 +0xc4            main.choice.adaptiveFormats({0x400009ac90, 0x0, 0x0}, 0x400036fb00, {0x7fed4e6e5f, 0xb})                /data/data/com.termux/files/home/mech/mech-master/cmd/youtube/youtube.go:42 +0x41c      main.main()
        /data/data/com.termux/files/home/mech/mech-master/cmd/youtube/main.go:74 +0x6b4
```

**Comment by 89z** [comment]
Please repost with correct line breaks. I will reopen once thats done. Thank you!

**Comment by 89z** [comment]
Never mind, I did it:

~~~
PS D:\Desktop> youtube gjtMDtA0N7Y
POST https://www.youtube.com/youtubei/v1/player
GET https://rr4---sn-q4flrney.googlevideo.com/videop...rh9BXpDGL_62BJYzVpIW2pG_QUjZLLIOaRPoiIXbQQ%3D%3D
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x50 pc=0x77a31b]

goroutine 1 [running]:
github.com/89z/format.Content(...)
        C:/Users/Steven/go/pkg/mod/github.com/89z/format@v1.16.8/format.go:123
github.com/89z/mech/youtube.Format.Write({0xf7, {0xc000229500, 0x34c}, {0xc00008e198, 0x18}, 0xbf8ee, 0x500, 0x2d0, 0x1674c00}, {0x841000, ...})
        D:/Git/mech/youtube/format.go:46 +0x11b
main.choice.adaptiveFormats({0xc000078db0, 0x0, 0x0}, 0xc000198000, {0x0, 0x7e3783})
        D:/Git/mech/cmd/youtube/youtube.go:42 +0x49f
main.main()
        D:/Git/mech/cmd/youtube/main.go:74 +0x54b
~~~

**Comment by 89z** [comment]
Problem is here:

https://github.com/89z/format/blob/v1.16.8/format.go#L123

sorry about that, should be easy fix.

**Comment by 89z** [comment]
This should be fixed now:

https://github.com/89z/mech/commit/895057a4a30a223f5039d3cc4a41d2dc84955fa2

**Comment by bartlomiejb** [comment]
> This should be fixed now:
> 
> [895057a](https://github.com/89z/mech/commit/895057a4a30a223f5039d3cc4a41d2dc84955fa2)

Yeah, it works now, even with age restricted video that I tried (with - e option).

Thanks for a quick reply and a fix. 👍🏻
